--USER_INFO TABLE
CREATE TABLE USER_INFO
(
    ID INTEGER PRIMARY KEY,
    USER_ID VARCHAR(50) UNIQUE NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_ROLE VARCHAR(50) DEFAULT 'USER' NOT NULL,
    USE_YN VARCHAR(1) DEFAULT 'Y' NOT NULL,
    INS_DTM TIMESTAMP DEFAULT NOW() NOT NULL
);


--SEQUENCE
CREATE SEQUENCE SEQ_USER_INFO
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;